// @generated by vars — do not edit
// @vars-platform: serverless
import { z } from "zod";

class Redacted<T> {
	#value: T;
	constructor(value: T) {
		this.#value = value;
	}
	unwrap(): T {
		return this.#value;
	}
	toString(): string {
		return "<redacted>";
	}
	toJSON(): string {
		return "<redacted>";
	}
	[Symbol.for("nodejs.util.inspect.custom")](): string {
		return "<redacted>";
	}
}

const schema = z.object({
	BETTER_AUTH_SECRET: z.string(),
	GITHUB_CLIENT_ID: z.string(),
	GITHUB_CLIENT_SECRET: z.string(),
	PUBLIC_URL: z.string(),
	LOCAL_DEV: z.string(),
});

export type Vars = {
	BETTER_AUTH_SECRET: Redacted<string>;
	GITHUB_CLIENT_ID: Redacted<string>;
	GITHUB_CLIENT_SECRET: Redacted<string>;
	PUBLIC_URL: string;
	LOCAL_DEV: string;
};

const PUBLIC_VARS = {
	PUBLIC_URL: {
		dev: "http://localhost:3000",
	},
	LOCAL_DEV: {
		dev: "true",
	},
} as const;

const CIPHERTEXTS = {
	dev: {
		BETTER_AUTH_SECRET:
			"enc:v2:aes256gcm-det:gnRS9J+MCLDeX04m:Edhv6lUQCTLVmtxEy1x2cRuRrRFWSeeUep5LFRB5x36aXtZOFWw+WTfzHBolzflqxA==:zbXkdgSzi0Nk7H9uTog2tw==",
		GITHUB_CLIENT_ID: "enc:v2:aes256gcm-det:gdKW1EnVYIbKzeZR::vZw1PVYgsC4+BiGjz0kpEA==",
		GITHUB_CLIENT_SECRET: "enc:v2:aes256gcm-det:I+MVw3221s/H3iOK::LzoabsekXRu0ydbH6xz2qQ==",
	},
} as const;

function base64ToBytes(b64: string): Uint8Array {
	const bin = typeof atob === "function" ? atob(b64) : Buffer.from(b64, "base64").toString("binary");
	const out = new Uint8Array(bin.length);
	for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
	return out;
}

async function hkdfSha256(master: Uint8Array, salt: string, info: string, length: number): Promise<Uint8Array> {
	const saltBytes = new TextEncoder().encode(salt);
	const infoBytes = new TextEncoder().encode(info);
	const baseKey = await crypto.subtle.importKey("raw", master as BufferSource, "HKDF", false, ["deriveBits"]);
	const bits = await crypto.subtle.deriveBits(
		{ name: "HKDF", hash: "SHA-256", salt: saltBytes, info: infoBytes },
		baseKey,
		length * 8,
	);
	return new Uint8Array(bits);
}

async function decryptToken(token: string, masterKey: Uint8Array): Promise<string> {
	const PREFIX = "enc:v2:aes256gcm-det:";
	if (!token.startsWith(PREFIX)) throw new Error("vars: invalid token format");
	const rest = token.slice(PREFIX.length);
	const parts = rest.split(":");
	let owner: string | null = null;
	let iv: string;
	let ct: string;
	let tag: string;
	if (parts.length === 4 && parts[0]!.startsWith("owner=")) {
		owner = parts[0]!.slice("owner=".length);
		iv = parts[1]!;
		ct = parts[2]!;
		tag = parts[3]!;
	} else if (parts.length === 3) {
		iv = parts[0]!;
		ct = parts[1]!;
		tag = parts[2]!;
	} else {
		throw new Error("vars: malformed token");
	}
	let aesKey = masterKey;
	if (owner) aesKey = await hkdfSha256(masterKey, "dotvars-owner-key-v1", "owner:" + owner, 32);
	const key = await crypto.subtle.importKey("raw", aesKey as BufferSource, { name: "AES-GCM" }, false, ["decrypt"]);
	const ivBytes = base64ToBytes(iv);
	const ctBytes = base64ToBytes(ct);
	const tagBytes = base64ToBytes(tag);
	const combined = new Uint8Array(ctBytes.length + tagBytes.length);
	combined.set(ctBytes, 0);
	combined.set(tagBytes, ctBytes.length);
	try {
		const pt = await crypto.subtle.decrypt(
			{ name: "AES-GCM", iv: ivBytes as BufferSource },
			key,
			combined as BufferSource,
		);
		return new TextDecoder().decode(pt);
	} catch {
		throw new Error("vars: decryption failed — wrong VARS_KEY or tampered ciphertext");
	}
}

function selectPublicValue(value: unknown, targetEnv: string): unknown {
	if (!value || typeof value !== "object") return value;
	const obj = value as Record<string, unknown>;
	if (Object.prototype.hasOwnProperty.call(obj, targetEnv)) return obj[targetEnv];
	const out: Record<string, unknown> = {};
	for (const [k, v] of Object.entries(obj)) {
		out[k] = selectPublicValue(v, targetEnv);
	}
	return out;
}

function wrapRedacted(parsed: Record<string, unknown>): Vars {
	return {
		BETTER_AUTH_SECRET: new Redacted(parsed["BETTER_AUTH_SECRET"] as string),
		GITHUB_CLIENT_ID: new Redacted(parsed["GITHUB_CLIENT_ID"] as string),
		GITHUB_CLIENT_SECRET: new Redacted(parsed["GITHUB_CLIENT_SECRET"] as string),
		PUBLIC_URL: parsed["PUBLIC_URL"] as string,
		LOCAL_DEV: parsed["LOCAL_DEV"] as string,
	};
}
function normalizeRaw(raw: Record<string, unknown>): void {}

const cache = new Map<string, Promise<Vars>>();

export async function getVars(
	env: { VARS_KEY?: string; VARS_ENV?: string } & Record<string, unknown>,
	envOverride?: "dev",
): Promise<Vars> {
	const targetEnv = envOverride ?? (env.VARS_ENV as "dev" | undefined);
	if (!targetEnv) throw new Error("vars: VARS_ENV not set and no override passed");
	if (!(targetEnv in CIPHERTEXTS)) throw new Error('vars: unknown env "' + targetEnv + '"');
	if (!env.VARS_KEY) throw new Error("vars: VARS_KEY not set in runtime env");
	const cacheKey = targetEnv + ":" + env.VARS_KEY;
	const hit = cache.get(cacheKey);
	if (hit) return hit;
	const inflight = (async () => {
		const masterKey = base64ToBytes(env.VARS_KEY as string);
		const raw: Record<string, unknown> = {};
		for (const [k, v] of Object.entries(PUBLIC_VARS)) {
			raw[k] = selectPublicValue(v, targetEnv);
		}
		const envCiphers = CIPHERTEXTS[targetEnv] as Record<string, string | Record<string, string>>;
		for (const [name, value] of Object.entries(envCiphers)) {
			if (typeof value === "string") {
				raw[name] = await decryptToken(value, masterKey);
			} else {
				const sub = (raw[name] as Record<string, string> | undefined) ?? {};
				for (const [member, token] of Object.entries(value)) {
					sub[member] = await decryptToken(token, masterKey);
				}
				raw[name] = sub;
			}
		}
		normalizeRaw(raw);
		const parsed = schema.parse(raw);
		return wrapRedacted(parsed);
	})();
	cache.set(cacheKey, inflight);
	inflight.catch(() => {
		if (cache.get(cacheKey) === inflight) cache.delete(cacheKey);
	});
	return inflight;
}
