// @generated by vars — do not edit
// @vars-platform: serverless
import { z } from 'zod';

class Redacted<T> {
  #value: T;
  constructor(value: T) {
    this.#value = value;
  }
  unwrap(): T {
    return this.#value;
  }
  toString(): string {
    return '<redacted>';
  }
  toJSON(): string {
    return '<redacted>';
  }
  [Symbol.for('nodejs.util.inspect.custom')](): string {
    return '<redacted>';
  }
}

const schema = z.object({
  PUBLIC_URL: z.string(),
  CLERK_PUBLISHABLE_KEY: z.string(),
  CLERK_SECRET_KEY: z.string(),
  CLERK_WEBHOOK_SIGNING_SECRET: z.string(),
  CLERK_OAUTH_CLIENT_ID: z.string(),
});

export type Vars = {
  PUBLIC_URL: string;
  CLERK_PUBLISHABLE_KEY: string;
  CLERK_SECRET_KEY: Redacted<string>;
  CLERK_WEBHOOK_SIGNING_SECRET: Redacted<string>;
  CLERK_OAUTH_CLIENT_ID: Redacted<string>;
};

const PUBLIC_VARS = {
  PUBLIC_URL: {
    "dev": "http://localhost:3000",
    "prod": "https://plantifiles.com",
  },
  CLERK_PUBLISHABLE_KEY: {
    "dev": "pk_test_ZmFuY3ktbWFtbW90aC04ODE3LmNsZXJrLmFjY291bnRzLmRldiQ",
    "prod": "pk_live_Y2xlcmsucGxhbnRpZmlsZXMuY29tJA",
  },
} as const;

const CIPHERTEXTS = {
  "dev": {
    CLERK_SECRET_KEY: "enc:v2:aes256gcm-det:mFjuuLY4S099ERIc:nQjGGKjNxxY4ZIHnbdFdZBpc63BwZ9Uq/KF8NG8cL9gPRwm4t0KQQ2tyCJGUj/0pKM4=:IVxKbJ8XvcSSQuhYaFLMvA==",
    CLERK_WEBHOOK_SIGNING_SECRET: "enc:v2:aes256gcm-det:TSJQsl1WGk6/76A+:XnkNGVudLxkkEZBHRAR6nnM15GaKc637Xll3If/Qf70087DWRD4=:233c+OpHmjb3fn3b03b2sA==",
    CLERK_OAUTH_CLIENT_ID: "enc:v2:aes256gcm-det:hoyHS4yaTASsL9RJ:Wgw5r9Y7CPuqM55i6nxfDw==:llTDnZvJl3u9IF8yJTbg4w==",
  },
  "prod": {
    CLERK_SECRET_KEY: "enc:v2:aes256gcm-det:PHF641+O2Y41r5Pm:hawT/wwzNnMFYXamcsfDBBXyhx5ef+s15rQgu8TSKwh99MDWvVahPPqxSoGnvWxrrRw=:c+nAAtpSnZrtZjTGeAYzsQ==",
    CLERK_WEBHOOK_SIGNING_SECRET: "enc:v2:aes256gcm-det:I6YH1dL5ooNSqYnV:BAmmUjGQKoOM22hqu07P4Wni3zeP7SUX5vHNU1ds00qujUQINuU=:+YRu7BDHxBhZPtfPcBhvGw==",
    CLERK_OAUTH_CLIENT_ID: "enc:v2:aes256gcm-det:rytbbMrzPWqf6+Bf:00EHAt2CpT/stqScNxXOJg==:B7v6ml8CsHtp0OR45/xD6Q==",
  },
} as const;


function base64ToBytes(b64: string): Uint8Array {
  const bin = typeof atob === "function" ? atob(b64) : Buffer.from(b64, "base64").toString("binary");
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function hkdfSha256(master: Uint8Array, salt: string, info: string, length: number): Promise<Uint8Array> {
  const saltBytes = new TextEncoder().encode(salt);
  const infoBytes = new TextEncoder().encode(info);
  const baseKey = await crypto.subtle.importKey("raw", master as BufferSource, "HKDF", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits(
    { name: "HKDF", hash: "SHA-256", salt: saltBytes, info: infoBytes },
    baseKey,
    length * 8,
  );
  return new Uint8Array(bits);
}

async function decryptToken(token: string, masterKey: Uint8Array): Promise<string> {
  const PREFIX = "enc:v2:aes256gcm-det:";
  if (!token.startsWith(PREFIX)) throw new Error("vars: invalid token format");
  const rest = token.slice(PREFIX.length);
  const parts = rest.split(":");
  let owner: string | null = null;
  let iv: string;
  let ct: string;
  let tag: string;
  if (parts.length === 4 && parts[0]!.startsWith("owner=")) {
    owner = parts[0]!.slice("owner=".length);
    iv = parts[1]!;
    ct = parts[2]!;
    tag = parts[3]!;
  } else if (parts.length === 3) {
    iv = parts[0]!;
    ct = parts[1]!;
    tag = parts[2]!;
  } else {
    throw new Error("vars: malformed token");
  }
  let aesKey = masterKey;
  if (owner) aesKey = await hkdfSha256(masterKey, "dotvars-owner-key-v1", "owner:" + owner, 32);
  const key = await crypto.subtle.importKey("raw", aesKey as BufferSource, { name: "AES-GCM" }, false, ["decrypt"]);
  const ivBytes = base64ToBytes(iv);
  const ctBytes = base64ToBytes(ct);
  const tagBytes = base64ToBytes(tag);
  const combined = new Uint8Array(ctBytes.length + tagBytes.length);
  combined.set(ctBytes, 0);
  combined.set(tagBytes, ctBytes.length);
  try {
    const pt = await crypto.subtle.decrypt({ name: "AES-GCM", iv: ivBytes as BufferSource }, key, combined as BufferSource);
    return new TextDecoder().decode(pt);
  } catch {
    throw new Error("vars: decryption failed — wrong VARS_KEY or tampered ciphertext");
  }
}

function selectPublicValue(value: unknown, targetEnv: string): unknown {
  if (!value || typeof value !== "object") return value;
  const obj = value as Record<string, unknown>;
  if (Object.prototype.hasOwnProperty.call(obj, targetEnv)) return obj[targetEnv];
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    out[k] = selectPublicValue(v, targetEnv);
  }
  return out;
}


function wrapRedacted(parsed: Record<string, unknown>): Vars {
  return {
    PUBLIC_URL: parsed.PUBLIC_URL as string,
    CLERK_PUBLISHABLE_KEY: parsed.CLERK_PUBLISHABLE_KEY as string,
    CLERK_SECRET_KEY: new Redacted(parsed.CLERK_SECRET_KEY as string),
    CLERK_WEBHOOK_SIGNING_SECRET: new Redacted(parsed.CLERK_WEBHOOK_SIGNING_SECRET as string),
    CLERK_OAUTH_CLIENT_ID: new Redacted(parsed.CLERK_OAUTH_CLIENT_ID as string),
  };
}

const cache = new Map<string, Promise<Vars>>();

export async function getVars(
  env: { VARS_KEY?: string; VARS_ENV?: string } & Record<string, unknown>,
  envOverride?: "dev" | "prod",
): Promise<Vars> {
  const targetEnv = envOverride ?? (env.VARS_ENV as "dev" | "prod" | undefined);
  if (!targetEnv) throw new Error("vars: VARS_ENV not set and no override passed");
  if (!(targetEnv in CIPHERTEXTS)) throw new Error("vars: unknown env \"" + targetEnv + "\"");
  if (!env.VARS_KEY) throw new Error("vars: VARS_KEY not set in runtime env");
  const cacheKey = targetEnv + ":" + env.VARS_KEY;
  const hit = cache.get(cacheKey);
  if (hit) return hit;
  const inflight = (async () => {
    const masterKey = base64ToBytes(env.VARS_KEY as string);
    const raw: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(PUBLIC_VARS)) {
      raw[k] = selectPublicValue(v, targetEnv);
    }
    const envCiphers = CIPHERTEXTS[targetEnv] as Record<string, string | Record<string, string>>;
    for (const [name, value] of Object.entries(envCiphers)) {
      if (typeof value === "string") {
        raw[name] = await decryptToken(value, masterKey);
      } else {
        const sub = (raw[name] as Record<string, string> | undefined) ?? {};
        for (const [member, token] of Object.entries(value)) {
          sub[member] = await decryptToken(token, masterKey);
        }
        raw[name] = sub;
      }
    }
    const parsed = schema.parse(raw);
    return wrapRedacted(parsed);
  })();
  cache.set(cacheKey, inflight);
  inflight.catch(() => {
    if (cache.get(cacheKey) === inflight) cache.delete(cacheKey);
  });
  return inflight;
}
