import { Diagram } from "./plan-diagram";
import {
	Callout,
	CodeSketch,
	LegacyPrototype,
	Option,
	Phase,
	PlanBlockquote,
	PlanCode,
	PlanHeading2,
	PlanHeading3,
	PlanInput,
	PlanLink,
	PlanList,
	PlanListItem,
	PlanOrderedList,
	PlanParagraph,
	PlanPre,
	PlanStrong,
	PlanTable,
	PlanTd,
	PlanTh,
	PlanThead,
	PlanTr,
	Rejected,
	Risk,
	TLDR,
	Tradeoff,
} from "./plan-prose-components";
import { Decision, PlanBlock } from "./plan-review-components";

const planComponents = {
	div: PlanBlock,
	p: PlanParagraph,
	h2: PlanHeading2,
	h3: PlanHeading3,
	ul: PlanList,
	ol: PlanOrderedList,
	li: PlanListItem,
	pre: PlanPre,
	code: PlanCode,
	a: PlanLink,
	input: PlanInput,
	strong: PlanStrong,
	blockquote: PlanBlockquote,
	table: PlanTable,
	thead: PlanThead,
	th: PlanTh,
	tr: PlanTr,
	td: PlanTd,
	TLDR,
	Decision,
	Tradeoff,
	Option,
	Rejected,
	Phase,
	Risk,
	Diagram,
	CodeSketch,
	Callout,
	Prototype: LegacyPrototype,
};

export { planComponents };
