/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as SettingsTokensRouteRouteImport } from './routes/settings/tokens/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPlansIndexRouteImport } from './routes/api/plans/index'
import { Route as ApiPlansIdRouteRouteImport } from './routes/api/plans/$id/route'
import { Route as PWorkspaceSlugPlanSlugRouteRouteImport } from './routes/p/$workspaceSlug/$planSlug/route'
import { Route as SkillsWritePlanSKILLDotmdRouteImport } from './routes/skills/write-plan/SKILL[.]md'
import { Route as WSlugIndexRouteImport } from './routes/w/$slug/index'
import { Route as WSlugDecisionsRouteRouteImport } from './routes/w/$slug/decisions/route'
import { Route as WSlugSettingsRouteRouteImport } from './routes/w/$slug/settings/route'
import { Route as ApiPlansIdCommentsRouteImport } from './routes/api/plans/$id/comments'
import { Route as ApiPlansIdVersionsRouteImport } from './routes/api/plans/$id/versions'
import { Route as PWorkspaceSlugPlanSlugIndexRouteImport } from './routes/p/$workspaceSlug/$planSlug/index'
import { Route as PWorkspaceSlugPlanSlugVNumberRouteRouteImport } from './routes/p/$workspaceSlug/$planSlug/v/$number/route'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTokensRouteRoute = SettingsTokensRouteRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIndexRoute = ApiPlansIndexRouteImport.update({
  id: '/api/plans/',
  path: '/api/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIdRouteRoute = ApiPlansIdRouteRouteImport.update({
  id: '/api/plans/$id',
  path: '/api/plans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PWorkspaceSlugPlanSlugRouteRoute =
  PWorkspaceSlugPlanSlugRouteRouteImport.update({
    id: '/p/$workspaceSlug/$planSlug',
    path: '/p/$workspaceSlug/$planSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const SkillsWritePlanSKILLDotmdRoute =
  SkillsWritePlanSKILLDotmdRouteImport.update({
    id: '/skills/write-plan/SKILL.md',
    path: '/skills/write-plan/SKILL.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const WSlugIndexRoute = WSlugIndexRouteImport.update({
  id: '/w/$slug/',
  path: '/w/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugDecisionsRouteRoute = WSlugDecisionsRouteRouteImport.update({
  id: '/w/$slug/decisions',
  path: '/w/$slug/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugSettingsRouteRoute = WSlugSettingsRouteRouteImport.update({
  id: '/w/$slug/settings',
  path: '/w/$slug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIdCommentsRoute = ApiPlansIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiPlansIdRouteRoute,
} as any)
const ApiPlansIdVersionsRoute = ApiPlansIdVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => ApiPlansIdRouteRoute,
} as any)
const PWorkspaceSlugPlanSlugIndexRoute =
  PWorkspaceSlugPlanSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PWorkspaceSlugPlanSlugRouteRoute,
  } as any)
const PWorkspaceSlugPlanSlugVNumberRouteRoute =
  PWorkspaceSlugPlanSlugVNumberRouteRouteImport.update({
    id: '/v/$number',
    path: '/v/$number',
    getParentRoute: () => PWorkspaceSlugPlanSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteRoute
  '/settings/tokens': typeof SettingsTokensRouteRoute
  '/': typeof homeIndexRoute
  '/api/plans/$id': typeof ApiPlansIdRouteRouteWithChildren
  '/p/$workspaceSlug/$planSlug': typeof PWorkspaceSlugPlanSlugRouteRouteWithChildren
  '/w/$slug/decisions': typeof WSlugDecisionsRouteRoute
  '/w/$slug/settings': typeof WSlugSettingsRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/skills/write-plan/SKILL.md': typeof SkillsWritePlanSKILLDotmdRoute
  '/api/plans/': typeof ApiPlansIndexRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/api/plans/$id/comments': typeof ApiPlansIdCommentsRoute
  '/api/plans/$id/versions': typeof ApiPlansIdVersionsRoute
  '/p/$workspaceSlug/$planSlug/': typeof PWorkspaceSlugPlanSlugIndexRoute
  '/p/$workspaceSlug/$planSlug/v/$number': typeof PWorkspaceSlugPlanSlugVNumberRouteRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteRoute
  '/settings/tokens': typeof SettingsTokensRouteRoute
  '/': typeof homeIndexRoute
  '/api/plans/$id': typeof ApiPlansIdRouteRouteWithChildren
  '/w/$slug/decisions': typeof WSlugDecisionsRouteRoute
  '/w/$slug/settings': typeof WSlugSettingsRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/skills/write-plan/SKILL.md': typeof SkillsWritePlanSKILLDotmdRoute
  '/api/plans': typeof ApiPlansIndexRoute
  '/w/$slug': typeof WSlugIndexRoute
  '/api/plans/$id/comments': typeof ApiPlansIdCommentsRoute
  '/api/plans/$id/versions': typeof ApiPlansIdVersionsRoute
  '/p/$workspaceSlug/$planSlug': typeof PWorkspaceSlugPlanSlugIndexRoute
  '/p/$workspaceSlug/$planSlug/v/$number': typeof PWorkspaceSlugPlanSlugVNumberRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRouteRoute
  '/settings/tokens': typeof SettingsTokensRouteRoute
  '/(home)/': typeof homeIndexRoute
  '/api/plans/$id': typeof ApiPlansIdRouteRouteWithChildren
  '/p/$workspaceSlug/$planSlug': typeof PWorkspaceSlugPlanSlugRouteRouteWithChildren
  '/w/$slug/decisions': typeof WSlugDecisionsRouteRoute
  '/w/$slug/settings': typeof WSlugSettingsRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/skills/write-plan/SKILL.md': typeof SkillsWritePlanSKILLDotmdRoute
  '/api/plans/': typeof ApiPlansIndexRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/api/plans/$id/comments': typeof ApiPlansIdCommentsRoute
  '/api/plans/$id/versions': typeof ApiPlansIdVersionsRoute
  '/p/$workspaceSlug/$planSlug/': typeof PWorkspaceSlugPlanSlugIndexRoute
  '/p/$workspaceSlug/$planSlug/v/$number': typeof PWorkspaceSlugPlanSlugVNumberRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/settings/tokens'
    | '/'
    | '/api/plans/$id'
    | '/p/$workspaceSlug/$planSlug'
    | '/w/$slug/decisions'
    | '/w/$slug/settings'
    | '/api/auth/$'
    | '/skills/write-plan/SKILL.md'
    | '/api/plans/'
    | '/w/$slug/'
    | '/api/plans/$id/comments'
    | '/api/plans/$id/versions'
    | '/p/$workspaceSlug/$planSlug/'
    | '/p/$workspaceSlug/$planSlug/v/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings/tokens'
    | '/'
    | '/api/plans/$id'
    | '/w/$slug/decisions'
    | '/w/$slug/settings'
    | '/api/auth/$'
    | '/skills/write-plan/SKILL.md'
    | '/api/plans'
    | '/w/$slug'
    | '/api/plans/$id/comments'
    | '/api/plans/$id/versions'
    | '/p/$workspaceSlug/$planSlug'
    | '/p/$workspaceSlug/$planSlug/v/$number'
  id:
    | '__root__'
    | '/login'
    | '/settings/tokens'
    | '/(home)/'
    | '/api/plans/$id'
    | '/p/$workspaceSlug/$planSlug'
    | '/w/$slug/decisions'
    | '/w/$slug/settings'
    | '/api/auth/$'
    | '/skills/write-plan/SKILL.md'
    | '/api/plans/'
    | '/w/$slug/'
    | '/api/plans/$id/comments'
    | '/api/plans/$id/versions'
    | '/p/$workspaceSlug/$planSlug/'
    | '/p/$workspaceSlug/$planSlug/v/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRouteRoute: typeof LoginRouteRoute
  SettingsTokensRouteRoute: typeof SettingsTokensRouteRoute
  homeIndexRoute: typeof homeIndexRoute
  ApiPlansIdRouteRoute: typeof ApiPlansIdRouteRouteWithChildren
  PWorkspaceSlugPlanSlugRouteRoute: typeof PWorkspaceSlugPlanSlugRouteRouteWithChildren
  WSlugDecisionsRouteRoute: typeof WSlugDecisionsRouteRoute
  WSlugSettingsRouteRoute: typeof WSlugSettingsRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SkillsWritePlanSKILLDotmdRoute: typeof SkillsWritePlanSKILLDotmdRoute
  ApiPlansIndexRoute: typeof ApiPlansIndexRoute
  WSlugIndexRoute: typeof WSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/': {
      id: '/api/plans/'
      path: '/api/plans'
      fullPath: '/api/plans/'
      preLoaderRoute: typeof ApiPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/$id': {
      id: '/api/plans/$id'
      path: '/api/plans/$id'
      fullPath: '/api/plans/$id'
      preLoaderRoute: typeof ApiPlansIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$workspaceSlug/$planSlug': {
      id: '/p/$workspaceSlug/$planSlug'
      path: '/p/$workspaceSlug/$planSlug'
      fullPath: '/p/$workspaceSlug/$planSlug'
      preLoaderRoute: typeof PWorkspaceSlugPlanSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/write-plan/SKILL.md': {
      id: '/skills/write-plan/SKILL.md'
      path: '/skills/write-plan/SKILL.md'
      fullPath: '/skills/write-plan/SKILL.md'
      preLoaderRoute: typeof SkillsWritePlanSKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/': {
      id: '/w/$slug/'
      path: '/w/$slug'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof WSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/decisions': {
      id: '/w/$slug/decisions'
      path: '/w/$slug/decisions'
      fullPath: '/w/$slug/decisions'
      preLoaderRoute: typeof WSlugDecisionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/settings': {
      id: '/w/$slug/settings'
      path: '/w/$slug/settings'
      fullPath: '/w/$slug/settings'
      preLoaderRoute: typeof WSlugSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/$id/comments': {
      id: '/api/plans/$id/comments'
      path: '/comments'
      fullPath: '/api/plans/$id/comments'
      preLoaderRoute: typeof ApiPlansIdCommentsRouteImport
      parentRoute: typeof ApiPlansIdRouteRoute
    }
    '/api/plans/$id/versions': {
      id: '/api/plans/$id/versions'
      path: '/versions'
      fullPath: '/api/plans/$id/versions'
      preLoaderRoute: typeof ApiPlansIdVersionsRouteImport
      parentRoute: typeof ApiPlansIdRouteRoute
    }
    '/p/$workspaceSlug/$planSlug/': {
      id: '/p/$workspaceSlug/$planSlug/'
      path: '/'
      fullPath: '/p/$workspaceSlug/$planSlug/'
      preLoaderRoute: typeof PWorkspaceSlugPlanSlugIndexRouteImport
      parentRoute: typeof PWorkspaceSlugPlanSlugRouteRoute
    }
    '/p/$workspaceSlug/$planSlug/v/$number': {
      id: '/p/$workspaceSlug/$planSlug/v/$number'
      path: '/v/$number'
      fullPath: '/p/$workspaceSlug/$planSlug/v/$number'
      preLoaderRoute: typeof PWorkspaceSlugPlanSlugVNumberRouteRouteImport
      parentRoute: typeof PWorkspaceSlugPlanSlugRouteRoute
    }
  }
}

interface ApiPlansIdRouteRouteChildren {
  ApiPlansIdCommentsRoute: typeof ApiPlansIdCommentsRoute
  ApiPlansIdVersionsRoute: typeof ApiPlansIdVersionsRoute
}

const ApiPlansIdRouteRouteChildren: ApiPlansIdRouteRouteChildren = {
  ApiPlansIdCommentsRoute: ApiPlansIdCommentsRoute,
  ApiPlansIdVersionsRoute: ApiPlansIdVersionsRoute,
}

const ApiPlansIdRouteRouteWithChildren = ApiPlansIdRouteRoute._addFileChildren(
  ApiPlansIdRouteRouteChildren,
)

interface PWorkspaceSlugPlanSlugRouteRouteChildren {
  PWorkspaceSlugPlanSlugIndexRoute: typeof PWorkspaceSlugPlanSlugIndexRoute
  PWorkspaceSlugPlanSlugVNumberRouteRoute: typeof PWorkspaceSlugPlanSlugVNumberRouteRoute
}

const PWorkspaceSlugPlanSlugRouteRouteChildren: PWorkspaceSlugPlanSlugRouteRouteChildren =
  {
    PWorkspaceSlugPlanSlugIndexRoute: PWorkspaceSlugPlanSlugIndexRoute,
    PWorkspaceSlugPlanSlugVNumberRouteRoute:
      PWorkspaceSlugPlanSlugVNumberRouteRoute,
  }

const PWorkspaceSlugPlanSlugRouteRouteWithChildren =
  PWorkspaceSlugPlanSlugRouteRoute._addFileChildren(
    PWorkspaceSlugPlanSlugRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LoginRouteRoute: LoginRouteRoute,
  SettingsTokensRouteRoute: SettingsTokensRouteRoute,
  homeIndexRoute: homeIndexRoute,
  ApiPlansIdRouteRoute: ApiPlansIdRouteRouteWithChildren,
  PWorkspaceSlugPlanSlugRouteRoute:
    PWorkspaceSlugPlanSlugRouteRouteWithChildren,
  WSlugDecisionsRouteRoute: WSlugDecisionsRouteRoute,
  WSlugSettingsRouteRoute: WSlugSettingsRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SkillsWritePlanSKILLDotmdRoute: SkillsWritePlanSKILLDotmdRoute,
  ApiPlansIndexRoute: ApiPlansIndexRoute,
  WSlugIndexRoute: WSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
