/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CliRouteRouteImport } from './routes/cli/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as SettingsTokensRouteRouteImport } from './routes/settings/tokens/route'
import { Route as ApiClerkWebhookRouteImport } from './routes/api/clerk/webhook'
import { Route as ApiPlansIndexRouteImport } from './routes/api/plans/index'
import { Route as ApiPlansIdRouteRouteImport } from './routes/api/plans/$id/route'
import { Route as ApiWorkspacesIndexRouteImport } from './routes/api/workspaces/index'
import { Route as PWorkspaceSlugPlanSlugRouteRouteImport } from './routes/p/$workspaceSlug/$planSlug/route'
import { Route as SkillsWritePlanSKILLDotmdRouteImport } from './routes/skills/write-plan/SKILL[.]md'
import { Route as WSlugIndexRouteImport } from './routes/w/$slug/index'
import { Route as ApiCliDeviceIndexRouteImport } from './routes/api/cli/device/index'
import { Route as ApiCliDeviceTokenRouteImport } from './routes/api/cli/device/token'
import { Route as ApiPlansIdCommentsRouteImport } from './routes/api/plans/$id/comments'
import { Route as ApiPlansIdVersionsRouteImport } from './routes/api/plans/$id/versions'
import { Route as PWorkspaceSlugPlanSlugIndexRouteImport } from './routes/p/$workspaceSlug/$planSlug/index'
import { Route as PWorkspaceSlugPlanSlugVNumberRouteRouteImport } from './routes/p/$workspaceSlug/$planSlug/v/$number/route'

const CliRouteRoute = CliRouteRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTokensRouteRoute = SettingsTokensRouteRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClerkWebhookRoute = ApiClerkWebhookRouteImport.update({
  id: '/api/clerk/webhook',
  path: '/api/clerk/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIndexRoute = ApiPlansIndexRouteImport.update({
  id: '/api/plans/',
  path: '/api/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIdRouteRoute = ApiPlansIdRouteRouteImport.update({
  id: '/api/plans/$id',
  path: '/api/plans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesIndexRoute = ApiWorkspacesIndexRouteImport.update({
  id: '/api/workspaces/',
  path: '/api/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const PWorkspaceSlugPlanSlugRouteRoute =
  PWorkspaceSlugPlanSlugRouteRouteImport.update({
    id: '/p/$workspaceSlug/$planSlug',
    path: '/p/$workspaceSlug/$planSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const SkillsWritePlanSKILLDotmdRoute =
  SkillsWritePlanSKILLDotmdRouteImport.update({
    id: '/skills/write-plan/SKILL.md',
    path: '/skills/write-plan/SKILL.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const WSlugIndexRoute = WSlugIndexRouteImport.update({
  id: '/w/$slug/',
  path: '/w/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliDeviceIndexRoute = ApiCliDeviceIndexRouteImport.update({
  id: '/api/cli/device/',
  path: '/api/cli/device/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliDeviceTokenRoute = ApiCliDeviceTokenRouteImport.update({
  id: '/api/cli/device/token',
  path: '/api/cli/device/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIdCommentsRoute = ApiPlansIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiPlansIdRouteRoute,
} as any)
const ApiPlansIdVersionsRoute = ApiPlansIdVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => ApiPlansIdRouteRoute,
} as any)
const PWorkspaceSlugPlanSlugIndexRoute =
  PWorkspaceSlugPlanSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PWorkspaceSlugPlanSlugRouteRoute,
  } as any)
const PWorkspaceSlugPlanSlugVNumberRouteRoute =
  PWorkspaceSlugPlanSlugVNumberRouteRouteImport.update({
    id: '/v/$number',
    path: '/v/$number',
    getParentRoute: () => PWorkspaceSlugPlanSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/cli': typeof CliRouteRoute
  '/settings/tokens': typeof SettingsTokensRouteRoute
  '/': typeof homeIndexRoute
  '/api/plans/$id': typeof ApiPlansIdRouteRouteWithChildren
  '/p/$workspaceSlug/$planSlug': typeof PWorkspaceSlugPlanSlugRouteRouteWithChildren
  '/api/clerk/webhook': typeof ApiClerkWebhookRoute
  '/skills/write-plan/SKILL.md': typeof SkillsWritePlanSKILLDotmdRoute
  '/api/plans/': typeof ApiPlansIndexRoute
  '/api/workspaces/': typeof ApiWorkspacesIndexRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/api/cli/device/token': typeof ApiCliDeviceTokenRoute
  '/api/plans/$id/comments': typeof ApiPlansIdCommentsRoute
  '/api/plans/$id/versions': typeof ApiPlansIdVersionsRoute
  '/api/cli/device/': typeof ApiCliDeviceIndexRoute
  '/p/$workspaceSlug/$planSlug/': typeof PWorkspaceSlugPlanSlugIndexRoute
  '/p/$workspaceSlug/$planSlug/v/$number': typeof PWorkspaceSlugPlanSlugVNumberRouteRoute
}
export interface FileRoutesByTo {
  '/cli': typeof CliRouteRoute
  '/settings/tokens': typeof SettingsTokensRouteRoute
  '/': typeof homeIndexRoute
  '/api/plans/$id': typeof ApiPlansIdRouteRouteWithChildren
  '/api/clerk/webhook': typeof ApiClerkWebhookRoute
  '/skills/write-plan/SKILL.md': typeof SkillsWritePlanSKILLDotmdRoute
  '/api/plans': typeof ApiPlansIndexRoute
  '/api/workspaces': typeof ApiWorkspacesIndexRoute
  '/w/$slug': typeof WSlugIndexRoute
  '/api/cli/device/token': typeof ApiCliDeviceTokenRoute
  '/api/plans/$id/comments': typeof ApiPlansIdCommentsRoute
  '/api/plans/$id/versions': typeof ApiPlansIdVersionsRoute
  '/api/cli/device': typeof ApiCliDeviceIndexRoute
  '/p/$workspaceSlug/$planSlug': typeof PWorkspaceSlugPlanSlugIndexRoute
  '/p/$workspaceSlug/$planSlug/v/$number': typeof PWorkspaceSlugPlanSlugVNumberRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/cli': typeof CliRouteRoute
  '/settings/tokens': typeof SettingsTokensRouteRoute
  '/(home)/': typeof homeIndexRoute
  '/api/plans/$id': typeof ApiPlansIdRouteRouteWithChildren
  '/p/$workspaceSlug/$planSlug': typeof PWorkspaceSlugPlanSlugRouteRouteWithChildren
  '/api/clerk/webhook': typeof ApiClerkWebhookRoute
  '/skills/write-plan/SKILL.md': typeof SkillsWritePlanSKILLDotmdRoute
  '/api/plans/': typeof ApiPlansIndexRoute
  '/api/workspaces/': typeof ApiWorkspacesIndexRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/api/cli/device/token': typeof ApiCliDeviceTokenRoute
  '/api/plans/$id/comments': typeof ApiPlansIdCommentsRoute
  '/api/plans/$id/versions': typeof ApiPlansIdVersionsRoute
  '/api/cli/device/': typeof ApiCliDeviceIndexRoute
  '/p/$workspaceSlug/$planSlug/': typeof PWorkspaceSlugPlanSlugIndexRoute
  '/p/$workspaceSlug/$planSlug/v/$number': typeof PWorkspaceSlugPlanSlugVNumberRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cli'
    | '/settings/tokens'
    | '/'
    | '/api/plans/$id'
    | '/p/$workspaceSlug/$planSlug'
    | '/api/clerk/webhook'
    | '/skills/write-plan/SKILL.md'
    | '/api/plans/'
    | '/api/workspaces/'
    | '/w/$slug/'
    | '/api/cli/device/token'
    | '/api/plans/$id/comments'
    | '/api/plans/$id/versions'
    | '/api/cli/device/'
    | '/p/$workspaceSlug/$planSlug/'
    | '/p/$workspaceSlug/$planSlug/v/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cli'
    | '/settings/tokens'
    | '/'
    | '/api/plans/$id'
    | '/api/clerk/webhook'
    | '/skills/write-plan/SKILL.md'
    | '/api/plans'
    | '/api/workspaces'
    | '/w/$slug'
    | '/api/cli/device/token'
    | '/api/plans/$id/comments'
    | '/api/plans/$id/versions'
    | '/api/cli/device'
    | '/p/$workspaceSlug/$planSlug'
    | '/p/$workspaceSlug/$planSlug/v/$number'
  id:
    | '__root__'
    | '/cli'
    | '/settings/tokens'
    | '/(home)/'
    | '/api/plans/$id'
    | '/p/$workspaceSlug/$planSlug'
    | '/api/clerk/webhook'
    | '/skills/write-plan/SKILL.md'
    | '/api/plans/'
    | '/api/workspaces/'
    | '/w/$slug/'
    | '/api/cli/device/token'
    | '/api/plans/$id/comments'
    | '/api/plans/$id/versions'
    | '/api/cli/device/'
    | '/p/$workspaceSlug/$planSlug/'
    | '/p/$workspaceSlug/$planSlug/v/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CliRouteRoute: typeof CliRouteRoute
  SettingsTokensRouteRoute: typeof SettingsTokensRouteRoute
  homeIndexRoute: typeof homeIndexRoute
  ApiPlansIdRouteRoute: typeof ApiPlansIdRouteRouteWithChildren
  PWorkspaceSlugPlanSlugRouteRoute: typeof PWorkspaceSlugPlanSlugRouteRouteWithChildren
  ApiClerkWebhookRoute: typeof ApiClerkWebhookRoute
  SkillsWritePlanSKILLDotmdRoute: typeof SkillsWritePlanSKILLDotmdRoute
  ApiPlansIndexRoute: typeof ApiPlansIndexRoute
  ApiWorkspacesIndexRoute: typeof ApiWorkspacesIndexRoute
  WSlugIndexRoute: typeof WSlugIndexRoute
  ApiCliDeviceTokenRoute: typeof ApiCliDeviceTokenRoute
  ApiCliDeviceIndexRoute: typeof ApiCliDeviceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clerk/webhook': {
      id: '/api/clerk/webhook'
      path: '/api/clerk/webhook'
      fullPath: '/api/clerk/webhook'
      preLoaderRoute: typeof ApiClerkWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/': {
      id: '/api/plans/'
      path: '/api/plans'
      fullPath: '/api/plans/'
      preLoaderRoute: typeof ApiPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/$id': {
      id: '/api/plans/$id'
      path: '/api/plans/$id'
      fullPath: '/api/plans/$id'
      preLoaderRoute: typeof ApiPlansIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/': {
      id: '/api/workspaces/'
      path: '/api/workspaces'
      fullPath: '/api/workspaces/'
      preLoaderRoute: typeof ApiWorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$workspaceSlug/$planSlug': {
      id: '/p/$workspaceSlug/$planSlug'
      path: '/p/$workspaceSlug/$planSlug'
      fullPath: '/p/$workspaceSlug/$planSlug'
      preLoaderRoute: typeof PWorkspaceSlugPlanSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/write-plan/SKILL.md': {
      id: '/skills/write-plan/SKILL.md'
      path: '/skills/write-plan/SKILL.md'
      fullPath: '/skills/write-plan/SKILL.md'
      preLoaderRoute: typeof SkillsWritePlanSKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/': {
      id: '/w/$slug/'
      path: '/w/$slug'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof WSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/device/': {
      id: '/api/cli/device/'
      path: '/api/cli/device'
      fullPath: '/api/cli/device/'
      preLoaderRoute: typeof ApiCliDeviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/device/token': {
      id: '/api/cli/device/token'
      path: '/api/cli/device/token'
      fullPath: '/api/cli/device/token'
      preLoaderRoute: typeof ApiCliDeviceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/$id/comments': {
      id: '/api/plans/$id/comments'
      path: '/comments'
      fullPath: '/api/plans/$id/comments'
      preLoaderRoute: typeof ApiPlansIdCommentsRouteImport
      parentRoute: typeof ApiPlansIdRouteRoute
    }
    '/api/plans/$id/versions': {
      id: '/api/plans/$id/versions'
      path: '/versions'
      fullPath: '/api/plans/$id/versions'
      preLoaderRoute: typeof ApiPlansIdVersionsRouteImport
      parentRoute: typeof ApiPlansIdRouteRoute
    }
    '/p/$workspaceSlug/$planSlug/': {
      id: '/p/$workspaceSlug/$planSlug/'
      path: '/'
      fullPath: '/p/$workspaceSlug/$planSlug/'
      preLoaderRoute: typeof PWorkspaceSlugPlanSlugIndexRouteImport
      parentRoute: typeof PWorkspaceSlugPlanSlugRouteRoute
    }
    '/p/$workspaceSlug/$planSlug/v/$number': {
      id: '/p/$workspaceSlug/$planSlug/v/$number'
      path: '/v/$number'
      fullPath: '/p/$workspaceSlug/$planSlug/v/$number'
      preLoaderRoute: typeof PWorkspaceSlugPlanSlugVNumberRouteRouteImport
      parentRoute: typeof PWorkspaceSlugPlanSlugRouteRoute
    }
  }
}

interface ApiPlansIdRouteRouteChildren {
  ApiPlansIdCommentsRoute: typeof ApiPlansIdCommentsRoute
  ApiPlansIdVersionsRoute: typeof ApiPlansIdVersionsRoute
}

const ApiPlansIdRouteRouteChildren: ApiPlansIdRouteRouteChildren = {
  ApiPlansIdCommentsRoute: ApiPlansIdCommentsRoute,
  ApiPlansIdVersionsRoute: ApiPlansIdVersionsRoute,
}

const ApiPlansIdRouteRouteWithChildren = ApiPlansIdRouteRoute._addFileChildren(
  ApiPlansIdRouteRouteChildren,
)

interface PWorkspaceSlugPlanSlugRouteRouteChildren {
  PWorkspaceSlugPlanSlugIndexRoute: typeof PWorkspaceSlugPlanSlugIndexRoute
  PWorkspaceSlugPlanSlugVNumberRouteRoute: typeof PWorkspaceSlugPlanSlugVNumberRouteRoute
}

const PWorkspaceSlugPlanSlugRouteRouteChildren: PWorkspaceSlugPlanSlugRouteRouteChildren =
  {
    PWorkspaceSlugPlanSlugIndexRoute: PWorkspaceSlugPlanSlugIndexRoute,
    PWorkspaceSlugPlanSlugVNumberRouteRoute:
      PWorkspaceSlugPlanSlugVNumberRouteRoute,
  }

const PWorkspaceSlugPlanSlugRouteRouteWithChildren =
  PWorkspaceSlugPlanSlugRouteRoute._addFileChildren(
    PWorkspaceSlugPlanSlugRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  CliRouteRoute: CliRouteRoute,
  SettingsTokensRouteRoute: SettingsTokensRouteRoute,
  homeIndexRoute: homeIndexRoute,
  ApiPlansIdRouteRoute: ApiPlansIdRouteRouteWithChildren,
  PWorkspaceSlugPlanSlugRouteRoute:
    PWorkspaceSlugPlanSlugRouteRouteWithChildren,
  ApiClerkWebhookRoute: ApiClerkWebhookRoute,
  SkillsWritePlanSKILLDotmdRoute: SkillsWritePlanSKILLDotmdRoute,
  ApiPlansIndexRoute: ApiPlansIndexRoute,
  ApiWorkspacesIndexRoute: ApiWorkspacesIndexRoute,
  WSlugIndexRoute: WSlugIndexRoute,
  ApiCliDeviceTokenRoute: ApiCliDeviceTokenRoute,
  ApiCliDeviceIndexRoute: ApiCliDeviceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
