/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPlansRouteImport } from './routes/api.plans'
import { Route as ApiTokensRouteImport } from './routes/api.tokens'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiPlansIdRouteImport } from './routes/api.plans.$id'
import { Route as ApiTokensIdRouteImport } from './routes/api.tokens.$id'
import { Route as PWorkspaceSlugPlanSlugRouteImport } from './routes/p.$workspaceSlug.$planSlug'
import { Route as ApiPlansIdCommentsRouteImport } from './routes/api.plans.$id.comments'
import { Route as ApiPlansIdVersionsRouteImport } from './routes/api.plans.$id.versions'
import { Route as PWorkspaceSlugPlanSlugVNumberRouteImport } from './routes/p.$workspaceSlug.$planSlug.v.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansRoute = ApiPlansRouteImport.update({
  id: '/api/plans',
  path: '/api/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIdRoute = ApiPlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPlansRoute,
} as any)
const ApiTokensIdRoute = ApiTokensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTokensRoute,
} as any)
const PWorkspaceSlugPlanSlugRoute = PWorkspaceSlugPlanSlugRouteImport.update({
  id: '/p/$workspaceSlug/$planSlug',
  path: '/p/$workspaceSlug/$planSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIdCommentsRoute = ApiPlansIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiPlansIdRoute,
} as any)
const ApiPlansIdVersionsRoute = ApiPlansIdVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => ApiPlansIdRoute,
} as any)
const PWorkspaceSlugPlanSlugVNumberRoute =
  PWorkspaceSlugPlanSlugVNumberRouteImport.update({
    id: '/v/$number',
    path: '/v/$number',
    getParentRoute: () => PWorkspaceSlugPlanSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/plans': typeof ApiPlansRouteWithChildren
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/plans/$id': typeof ApiPlansIdRouteWithChildren
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/p/$workspaceSlug/$planSlug': typeof PWorkspaceSlugPlanSlugRouteWithChildren
  '/api/plans/$id/comments': typeof ApiPlansIdCommentsRoute
  '/api/plans/$id/versions': typeof ApiPlansIdVersionsRoute
  '/p/$workspaceSlug/$planSlug/v/$number': typeof PWorkspaceSlugPlanSlugVNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/plans': typeof ApiPlansRouteWithChildren
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/plans/$id': typeof ApiPlansIdRouteWithChildren
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/p/$workspaceSlug/$planSlug': typeof PWorkspaceSlugPlanSlugRouteWithChildren
  '/api/plans/$id/comments': typeof ApiPlansIdCommentsRoute
  '/api/plans/$id/versions': typeof ApiPlansIdVersionsRoute
  '/p/$workspaceSlug/$planSlug/v/$number': typeof PWorkspaceSlugPlanSlugVNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/plans': typeof ApiPlansRouteWithChildren
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/plans/$id': typeof ApiPlansIdRouteWithChildren
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/p/$workspaceSlug/$planSlug': typeof PWorkspaceSlugPlanSlugRouteWithChildren
  '/api/plans/$id/comments': typeof ApiPlansIdCommentsRoute
  '/api/plans/$id/versions': typeof ApiPlansIdVersionsRoute
  '/p/$workspaceSlug/$planSlug/v/$number': typeof PWorkspaceSlugPlanSlugVNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/plans'
    | '/api/tokens'
    | '/api/auth/$'
    | '/api/plans/$id'
    | '/api/tokens/$id'
    | '/p/$workspaceSlug/$planSlug'
    | '/api/plans/$id/comments'
    | '/api/plans/$id/versions'
    | '/p/$workspaceSlug/$planSlug/v/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/plans'
    | '/api/tokens'
    | '/api/auth/$'
    | '/api/plans/$id'
    | '/api/tokens/$id'
    | '/p/$workspaceSlug/$planSlug'
    | '/api/plans/$id/comments'
    | '/api/plans/$id/versions'
    | '/p/$workspaceSlug/$planSlug/v/$number'
  id:
    | '__root__'
    | '/'
    | '/api/plans'
    | '/api/tokens'
    | '/api/auth/$'
    | '/api/plans/$id'
    | '/api/tokens/$id'
    | '/p/$workspaceSlug/$planSlug'
    | '/api/plans/$id/comments'
    | '/api/plans/$id/versions'
    | '/p/$workspaceSlug/$planSlug/v/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPlansRoute: typeof ApiPlansRouteWithChildren
  ApiTokensRoute: typeof ApiTokensRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PWorkspaceSlugPlanSlugRoute: typeof PWorkspaceSlugPlanSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans': {
      id: '/api/plans'
      path: '/api/plans'
      fullPath: '/api/plans'
      preLoaderRoute: typeof ApiPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/$id': {
      id: '/api/plans/$id'
      path: '/$id'
      fullPath: '/api/plans/$id'
      preLoaderRoute: typeof ApiPlansIdRouteImport
      parentRoute: typeof ApiPlansRoute
    }
    '/api/tokens/$id': {
      id: '/api/tokens/$id'
      path: '/$id'
      fullPath: '/api/tokens/$id'
      preLoaderRoute: typeof ApiTokensIdRouteImport
      parentRoute: typeof ApiTokensRoute
    }
    '/p/$workspaceSlug/$planSlug': {
      id: '/p/$workspaceSlug/$planSlug'
      path: '/p/$workspaceSlug/$planSlug'
      fullPath: '/p/$workspaceSlug/$planSlug'
      preLoaderRoute: typeof PWorkspaceSlugPlanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/$id/comments': {
      id: '/api/plans/$id/comments'
      path: '/comments'
      fullPath: '/api/plans/$id/comments'
      preLoaderRoute: typeof ApiPlansIdCommentsRouteImport
      parentRoute: typeof ApiPlansIdRoute
    }
    '/api/plans/$id/versions': {
      id: '/api/plans/$id/versions'
      path: '/versions'
      fullPath: '/api/plans/$id/versions'
      preLoaderRoute: typeof ApiPlansIdVersionsRouteImport
      parentRoute: typeof ApiPlansIdRoute
    }
    '/p/$workspaceSlug/$planSlug/v/$number': {
      id: '/p/$workspaceSlug/$planSlug/v/$number'
      path: '/v/$number'
      fullPath: '/p/$workspaceSlug/$planSlug/v/$number'
      preLoaderRoute: typeof PWorkspaceSlugPlanSlugVNumberRouteImport
      parentRoute: typeof PWorkspaceSlugPlanSlugRoute
    }
  }
}

interface ApiPlansIdRouteChildren {
  ApiPlansIdCommentsRoute: typeof ApiPlansIdCommentsRoute
  ApiPlansIdVersionsRoute: typeof ApiPlansIdVersionsRoute
}

const ApiPlansIdRouteChildren: ApiPlansIdRouteChildren = {
  ApiPlansIdCommentsRoute: ApiPlansIdCommentsRoute,
  ApiPlansIdVersionsRoute: ApiPlansIdVersionsRoute,
}

const ApiPlansIdRouteWithChildren = ApiPlansIdRoute._addFileChildren(
  ApiPlansIdRouteChildren,
)

interface ApiPlansRouteChildren {
  ApiPlansIdRoute: typeof ApiPlansIdRouteWithChildren
}

const ApiPlansRouteChildren: ApiPlansRouteChildren = {
  ApiPlansIdRoute: ApiPlansIdRouteWithChildren,
}

const ApiPlansRouteWithChildren = ApiPlansRoute._addFileChildren(
  ApiPlansRouteChildren,
)

interface ApiTokensRouteChildren {
  ApiTokensIdRoute: typeof ApiTokensIdRoute
}

const ApiTokensRouteChildren: ApiTokensRouteChildren = {
  ApiTokensIdRoute: ApiTokensIdRoute,
}

const ApiTokensRouteWithChildren = ApiTokensRoute._addFileChildren(
  ApiTokensRouteChildren,
)

interface PWorkspaceSlugPlanSlugRouteChildren {
  PWorkspaceSlugPlanSlugVNumberRoute: typeof PWorkspaceSlugPlanSlugVNumberRoute
}

const PWorkspaceSlugPlanSlugRouteChildren: PWorkspaceSlugPlanSlugRouteChildren =
  {
    PWorkspaceSlugPlanSlugVNumberRoute: PWorkspaceSlugPlanSlugVNumberRoute,
  }

const PWorkspaceSlugPlanSlugRouteWithChildren =
  PWorkspaceSlugPlanSlugRoute._addFileChildren(
    PWorkspaceSlugPlanSlugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPlansRoute: ApiPlansRouteWithChildren,
  ApiTokensRoute: ApiTokensRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PWorkspaceSlugPlanSlugRoute: PWorkspaceSlugPlanSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
